docker exec -ti lbg_master0.lbg.dev_1 bash -c 'cp /etc/resolv.conf.bak /etc/resolv.conf'
docker exec -ti lbg_master0.lbg.dev_1 bash -c 'ipa-client-install --enable-dns-updates --mkhomedir --ssh-trust-dns --principal=admin --password=adminadmin --unattended'
docker exec -ti lbg_master0.lbg.dev_1 bash -c 'service oddjobd start'
docker exec -ti lbg_dn0.lbg.dev_1 bash -c 'cp /etc/resolv.conf.bak /etc/resolv.conf'
docker exec -ti lbg_dn0.lbg.dev_1 bash -c 'ipa-client-install --enable-dns-updates --mkhomedir --ssh-trust-dns --principal=admin --password=adminadmin --unattended'
docker exec -ti lbg_dn0.lbg.dev_1 bash -c 'service oddjobd start'
docker exec -ti lbg_dn1.lbg.dev_1 bash -c 'cp /etc/resolv.conf.bak /etc/resolv.conf'
docker exec -ti lbg_dn1.lbg.dev_1 bash -c 'ipa-client-install --enable-dns-updates --mkhomedir --ssh-trust-dns --principal=admin --password=adminadmin --unattended'
docker exec -ti lbg_dn1.lbg.dev_1 bash -c 'service oddjobd start'
docker exec -ti lbg_dn2.lbg.dev_1 bash -c 'cp /etc/resolv.conf.bak /etc/resolv.conf'
docker exec -ti lbg_dn2.lbg.dev_1 bash -c 'ipa-client-install --enable-dns-updates --mkhomedir --ssh-trust-dns --principal=admin --password=adminadmin --unattended'
docker exec -ti lbg_dn2.lbg.dev_1 bash -c 'service oddjobd start'
docker exec -ti lbg_ambari-server.lbg.dev_1 bash -c 'cp /etc/resolv.conf.bak /etc/resolv.conf'
docker exec -ti lbg_ambari-server.lbg.dev_1 bash -c 'ipa-client-install --enable-dns-updates --mkhomedir --ssh-trust-dns --principal=admin --password=adminadmin --unattended'
docker exec -ti lbg_ambari-server.lbg.dev_1 bash -c 'service oddjobd start'
